name: Publish Docker image
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Install nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-20.09
      - run: |
        nix-build docker.nix ${{ github.event.ref }}
        nix-env -iA nixpkgs.docker

      - name: Push to Docker Hub 🐋
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push hub.docker.com/zeratax/matrix-registration
       
      # - name: Push to GitHub Packages 📦
      #   env:
      #     GITHUB_USERNAME: ${{ github.actor }}
      #     GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     echo "$GITHUB_USERNAME" | docker login ghcr.io -u "$GITHUB_PASSWORD" --password-stdin
      #     docker push ghcr.io/zeratax/matrix-registration/matrix-registration-image
